// Code generated by protoc-gen-go. DO NOT EDIT.
// source: renderer.proto

package renderer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RenderRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	Timezone             string   `protobuf:"bytes,5,opt,name=timezone" json:"timezone,omitempty"`
	Encoding             string   `protobuf:"bytes,6,opt,name=encoding" json:"encoding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderRequest) Reset()         { *m = RenderRequest{} }
func (m *RenderRequest) String() string { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()    {}
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_renderer_9b0fc59042fc65a5, []int{0}
}
func (m *RenderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderRequest.Unmarshal(m, b)
}
func (m *RenderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderRequest.Marshal(b, m, deterministic)
}
func (dst *RenderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderRequest.Merge(dst, src)
}
func (m *RenderRequest) XXX_Size() int {
	return xxx_messageInfo_RenderRequest.Size(m)
}
func (m *RenderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderRequest proto.InternalMessageInfo

func (m *RenderRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RenderRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *RenderRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RenderRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RenderRequest) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *RenderRequest) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

type RenderResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderResponse) Reset()         { *m = RenderResponse{} }
func (m *RenderResponse) String() string { return proto.CompactTextString(m) }
func (*RenderResponse) ProtoMessage()    {}
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_renderer_9b0fc59042fc65a5, []int{1}
}
func (m *RenderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderResponse.Unmarshal(m, b)
}
func (m *RenderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderResponse.Marshal(b, m, deterministic)
}
func (dst *RenderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderResponse.Merge(dst, src)
}
func (m *RenderResponse) XXX_Size() int {
	return xxx_messageInfo_RenderResponse.Size(m)
}
func (m *RenderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderResponse proto.InternalMessageInfo

func (m *RenderResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*RenderRequest)(nil), "models.RenderRequest")
	proto.RegisterType((*RenderResponse)(nil), "models.RenderResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RendererClient is the client API for Renderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RendererClient interface {
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type rendererClient struct {
	cc *grpc.ClientConn
}

func NewRendererClient(cc *grpc.ClientConn) RendererClient {
	return &rendererClient{cc}
}

func (c *rendererClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, "/models.Renderer/Render", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Renderer service

type RendererServer interface {
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
}

func RegisterRendererServer(s *grpc.Server, srv RendererServer) {
	s.RegisterService(&_Renderer_serviceDesc, srv)
}

func _Renderer_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendererServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Renderer/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendererServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Renderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Renderer",
	HandlerType: (*RendererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _Renderer_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "renderer.proto",
}

func init() { proto.RegisterFile("renderer.proto", fileDescriptor_renderer_9b0fc59042fc65a5) }

var fileDescriptor_renderer_9b0fc59042fc65a5 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x89, 0x75, 0xe3, 0x3a, 0x68, 0x91, 0x41, 0x4b, 0xe8, 0xa9, 0xf4, 0x54, 0x3c, 0xec,
	0x41, 0x0f, 0xde, 0xf5, 0x1f, 0xe4, 0xe8, 0xd1, 0x66, 0xe8, 0x06, 0xda, 0x4c, 0x4d, 0x66, 0x11,
	0xfc, 0x37, 0xfe, 0x53, 0x49, 0xd2, 0x08, 0xf6, 0xf6, 0xbe, 0x79, 0x30, 0x33, 0xef, 0xc1, 0x3c,
	0x52, 0x70, 0x14, 0x29, 0x0e, 0xc7, 0xc8, 0xc2, 0xa8, 0x0f, 0xec, 0x68, 0x9f, 0xd6, 0x3f, 0x0a,
	0x6e, 0x6d, 0xb1, 0x2c, 0x7d, 0x4e, 0x94, 0x04, 0xef, 0x60, 0x36, 0xc5, 0xbd, 0x51, 0x2b, 0xb5,
	0xb9, 0xb6, 0x59, 0xe2, 0x3d, 0x74, 0x5f, 0xde, 0xc9, 0x68, 0x2e, 0x56, 0x6a, 0xd3, 0xd9, 0x0a,
	0xb8, 0x00, 0x3d, 0x92, 0xdf, 0x8d, 0x62, 0x66, 0x65, 0x7c, 0x22, 0x34, 0x70, 0x25, 0xfe, 0x40,
	0x3c, 0x89, 0xb9, 0x2c, 0x46, 0x43, 0x5c, 0x42, 0x9f, 0xe5, 0x37, 0x07, 0x32, 0x5d, 0x59, 0xff,
	0xc7, 0xd9, 0xa3, 0xb0, 0x65, 0xe7, 0xc3, 0xce, 0xe8, 0xea, 0x35, 0x5e, 0x3f, 0xc2, 0xbc, 0xbd,
	0x98, 0x8e, 0x1c, 0x12, 0xe5, 0x1b, 0x5b, 0x0e, 0x42, 0x41, 0xca, 0x9f, 0x37, 0xb6, 0xe1, 0xd3,
	0x1b, 0xf4, 0xf6, 0x94, 0x14, 0x5f, 0x40, 0x57, 0x8d, 0x0f, 0x43, 0x8d, 0x3b, 0xfc, 0x8b, 0xba,
	0x5c, 0x9c, 0x8f, 0xeb, 0xfa, 0x57, 0x78, 0xef, 0x5b, 0x5d, 0x1f, 0xba, 0xf4, 0xf5, 0xfc, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xe0, 0x1b, 0x4e, 0x64, 0x41, 0x01, 0x00, 0x00,
}
