// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datasource.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	datasource.proto

It has these top-level messages:
	TsdbQuery
	Query
	TimeRange
	Response
	QueryResult
	Table
	TableColumn
	TableRow
	RowValue
	DatasourceInfo
	TimeSeries
	Point
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RowValue_Kind int32

const (
	// Field type null.
	RowValue_TYPE_NULL RowValue_Kind = 0
	// Field type double.
	RowValue_TYPE_DOUBLE RowValue_Kind = 1
	// Field type int64.
	RowValue_TYPE_INT64 RowValue_Kind = 2
	// Field type bool.
	RowValue_TYPE_BOOL RowValue_Kind = 3
	// Field type string.
	RowValue_TYPE_STRING RowValue_Kind = 4
	// Field type bytes.
	RowValue_TYPE_BYTES RowValue_Kind = 5
)

var RowValue_Kind_name = map[int32]string{
	0: "TYPE_NULL",
	1: "TYPE_DOUBLE",
	2: "TYPE_INT64",
	3: "TYPE_BOOL",
	4: "TYPE_STRING",
	5: "TYPE_BYTES",
}
var RowValue_Kind_value = map[string]int32{
	"TYPE_NULL":   0,
	"TYPE_DOUBLE": 1,
	"TYPE_INT64":  2,
	"TYPE_BOOL":   3,
	"TYPE_STRING": 4,
	"TYPE_BYTES":  5,
}

func (x RowValue_Kind) String() string {
	return proto.EnumName(RowValue_Kind_name, int32(x))
}
func (RowValue_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type TsdbQuery struct {
	TimeRange  *TimeRange      `protobuf:"bytes,1,opt,name=timeRange" json:"timeRange,omitempty"`
	Datasource *DatasourceInfo `protobuf:"bytes,2,opt,name=datasource" json:"datasource,omitempty"`
	Queries    []*Query        `protobuf:"bytes,3,rep,name=queries" json:"queries,omitempty"`
}

func (m *TsdbQuery) Reset()                    { *m = TsdbQuery{} }
func (m *TsdbQuery) String() string            { return proto.CompactTextString(m) }
func (*TsdbQuery) ProtoMessage()               {}
func (*TsdbQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TsdbQuery) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *TsdbQuery) GetDatasource() *DatasourceInfo {
	if m != nil {
		return m.Datasource
	}
	return nil
}

func (m *TsdbQuery) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

type Query struct {
	RefId         string `protobuf:"bytes,1,opt,name=refId" json:"refId,omitempty"`
	MaxDataPoints int64  `protobuf:"varint,2,opt,name=maxDataPoints" json:"maxDataPoints,omitempty"`
	IntervalMs    int64  `protobuf:"varint,3,opt,name=intervalMs" json:"intervalMs,omitempty"`
	ModelJson     string `protobuf:"bytes,4,opt,name=modelJson" json:"modelJson,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Query) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *Query) GetMaxDataPoints() int64 {
	if m != nil {
		return m.MaxDataPoints
	}
	return 0
}

func (m *Query) GetIntervalMs() int64 {
	if m != nil {
		return m.IntervalMs
	}
	return 0
}

func (m *Query) GetModelJson() string {
	if m != nil {
		return m.ModelJson
	}
	return ""
}

type TimeRange struct {
	FromRaw     string `protobuf:"bytes,1,opt,name=fromRaw" json:"fromRaw,omitempty"`
	ToRaw       string `protobuf:"bytes,2,opt,name=toRaw" json:"toRaw,omitempty"`
	FromEpochMs int64  `protobuf:"varint,3,opt,name=fromEpochMs" json:"fromEpochMs,omitempty"`
	ToEpochMs   int64  `protobuf:"varint,4,opt,name=toEpochMs" json:"toEpochMs,omitempty"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TimeRange) GetFromRaw() string {
	if m != nil {
		return m.FromRaw
	}
	return ""
}

func (m *TimeRange) GetToRaw() string {
	if m != nil {
		return m.ToRaw
	}
	return ""
}

func (m *TimeRange) GetFromEpochMs() int64 {
	if m != nil {
		return m.FromEpochMs
	}
	return 0
}

func (m *TimeRange) GetToEpochMs() int64 {
	if m != nil {
		return m.ToEpochMs
	}
	return 0
}

type Response struct {
	Results []*QueryResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type QueryResult struct {
	Error    string        `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	RefId    string        `protobuf:"bytes,2,opt,name=refId" json:"refId,omitempty"`
	MetaJson string        `protobuf:"bytes,3,opt,name=metaJson" json:"metaJson,omitempty"`
	Series   []*TimeSeries `protobuf:"bytes,4,rep,name=series" json:"series,omitempty"`
	Tables   []*Table      `protobuf:"bytes,5,rep,name=tables" json:"tables,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *QueryResult) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *QueryResult) GetMetaJson() string {
	if m != nil {
		return m.MetaJson
	}
	return ""
}

func (m *QueryResult) GetSeries() []*TimeSeries {
	if m != nil {
		return m.Series
	}
	return nil
}

func (m *QueryResult) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

type Table struct {
	Columns []*TableColumn `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	Rows    []*TableRow    `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
}

func (m *Table) Reset()                    { *m = Table{} }
func (m *Table) String() string            { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()               {}
func (*Table) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Table) GetColumns() []*TableColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Table) GetRows() []*TableRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type TableColumn struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *TableColumn) Reset()                    { *m = TableColumn{} }
func (m *TableColumn) String() string            { return proto.CompactTextString(m) }
func (*TableColumn) ProtoMessage()               {}
func (*TableColumn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TableColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TableRow struct {
	Values []*RowValue `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *TableRow) Reset()                    { *m = TableRow{} }
func (m *TableRow) String() string            { return proto.CompactTextString(m) }
func (*TableRow) ProtoMessage()               {}
func (*TableRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TableRow) GetValues() []*RowValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type RowValue struct {
	Kind        RowValue_Kind `protobuf:"varint,1,opt,name=kind,enum=models.RowValue_Kind" json:"kind,omitempty"`
	DoubleValue float64       `protobuf:"fixed64,2,opt,name=doubleValue" json:"doubleValue,omitempty"`
	Int64Value  int64         `protobuf:"varint,3,opt,name=int64Value" json:"int64Value,omitempty"`
	BoolValue   bool          `protobuf:"varint,4,opt,name=boolValue" json:"boolValue,omitempty"`
	StringValue string        `protobuf:"bytes,5,opt,name=stringValue" json:"stringValue,omitempty"`
	BytesValue  []byte        `protobuf:"bytes,6,opt,name=bytesValue,proto3" json:"bytesValue,omitempty"`
}

func (m *RowValue) Reset()                    { *m = RowValue{} }
func (m *RowValue) String() string            { return proto.CompactTextString(m) }
func (*RowValue) ProtoMessage()               {}
func (*RowValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RowValue) GetKind() RowValue_Kind {
	if m != nil {
		return m.Kind
	}
	return RowValue_TYPE_NULL
}

func (m *RowValue) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *RowValue) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *RowValue) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *RowValue) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *RowValue) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

type DatasourceInfo struct {
	Id             int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	OrgId          int64  `protobuf:"varint,2,opt,name=orgId" json:"orgId,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Type           string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Url            string `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	JsonData       string `protobuf:"bytes,6,opt,name=jsonData" json:"jsonData,omitempty"`
	SecureJsonData string `protobuf:"bytes,7,opt,name=secureJsonData" json:"secureJsonData,omitempty"`
}

func (m *DatasourceInfo) Reset()                    { *m = DatasourceInfo{} }
func (m *DatasourceInfo) String() string            { return proto.CompactTextString(m) }
func (*DatasourceInfo) ProtoMessage()               {}
func (*DatasourceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DatasourceInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DatasourceInfo) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *DatasourceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DatasourceInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DatasourceInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DatasourceInfo) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

func (m *DatasourceInfo) GetSecureJsonData() string {
	if m != nil {
		return m.SecureJsonData
	}
	return ""
}

type TimeSeries struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tags   map[string]string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points []*Point          `protobuf:"bytes,3,rep,name=points" json:"points,omitempty"`
}

func (m *TimeSeries) Reset()                    { *m = TimeSeries{} }
func (m *TimeSeries) String() string            { return proto.CompactTextString(m) }
func (*TimeSeries) ProtoMessage()               {}
func (*TimeSeries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TimeSeries) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TimeSeries) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TimeSeries) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type Point struct {
	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Point) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Point) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*TsdbQuery)(nil), "models.TsdbQuery")
	proto.RegisterType((*Query)(nil), "models.Query")
	proto.RegisterType((*TimeRange)(nil), "models.TimeRange")
	proto.RegisterType((*Response)(nil), "models.Response")
	proto.RegisterType((*QueryResult)(nil), "models.QueryResult")
	proto.RegisterType((*Table)(nil), "models.Table")
	proto.RegisterType((*TableColumn)(nil), "models.TableColumn")
	proto.RegisterType((*TableRow)(nil), "models.TableRow")
	proto.RegisterType((*RowValue)(nil), "models.RowValue")
	proto.RegisterType((*DatasourceInfo)(nil), "models.DatasourceInfo")
	proto.RegisterType((*TimeSeries)(nil), "models.TimeSeries")
	proto.RegisterType((*Point)(nil), "models.Point")
	proto.RegisterEnum("models.RowValue_Kind", RowValue_Kind_name, RowValue_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DatasourcePlugin service

type DatasourcePluginClient interface {
	Query(ctx context.Context, in *TsdbQuery, opts ...grpc.CallOption) (*Response, error)
}

type datasourcePluginClient struct {
	cc *grpc.ClientConn
}

func NewDatasourcePluginClient(cc *grpc.ClientConn) DatasourcePluginClient {
	return &datasourcePluginClient{cc}
}

func (c *datasourcePluginClient) Query(ctx context.Context, in *TsdbQuery, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/models.DatasourcePlugin/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DatasourcePlugin service

type DatasourcePluginServer interface {
	Query(context.Context, *TsdbQuery) (*Response, error)
}

func RegisterDatasourcePluginServer(s *grpc.Server, srv DatasourcePluginServer) {
	s.RegisterService(&_DatasourcePlugin_serviceDesc, srv)
}

func _DatasourcePlugin_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TsdbQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasourcePluginServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.DatasourcePlugin/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasourcePluginServer).Query(ctx, req.(*TsdbQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatasourcePlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.DatasourcePlugin",
	HandlerType: (*DatasourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _DatasourcePlugin_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datasource.proto",
}

func init() { proto.RegisterFile("datasource.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 806 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0x5d, 0x8f, 0xe3, 0x34,
	0x14, 0x25, 0x1f, 0xed, 0x34, 0xb7, 0x4c, 0x09, 0xe6, 0x43, 0xd5, 0x68, 0x85, 0x86, 0x68, 0x81,
	0x82, 0xa0, 0xa0, 0x32, 0x1a, 0xbe, 0x5e, 0x50, 0xd9, 0x0a, 0x75, 0x29, 0x33, 0x83, 0x27, 0x8b,
	0xb4, 0x08, 0x09, 0xa5, 0xad, 0x5b, 0xc2, 0x26, 0x71, 0xb1, 0x9d, 0x29, 0x15, 0x4f, 0xfc, 0x10,
	0xde, 0x79, 0x46, 0xbc, 0xf3, 0xd7, 0x90, 0x6f, 0xec, 0x24, 0x9d, 0xe5, 0xcd, 0xf7, 0x9c, 0xe3,
	0xeb, 0xeb, 0xeb, 0x63, 0x1b, 0xc2, 0x75, 0xa2, 0x12, 0xc9, 0x4b, 0xb1, 0x62, 0xe3, 0x9d, 0xe0,
	0x8a, 0x93, 0x6e, 0xce, 0xd7, 0x2c, 0x93, 0xd1, 0x9f, 0x0e, 0x04, 0xb1, 0x5c, 0x2f, 0xbf, 0x2b,
	0x99, 0x38, 0x90, 0x0f, 0x21, 0x50, 0x69, 0xce, 0x68, 0x52, 0x6c, 0xd9, 0xd0, 0x39, 0x77, 0x46,
	0xfd, 0xc9, 0xcb, 0xe3, 0x4a, 0x39, 0x8e, 0x2d, 0x41, 0x1b, 0x0d, 0xb9, 0x04, 0x68, 0x52, 0x0f,
	0x5d, 0x9c, 0xf1, 0xba, 0x9d, 0xf1, 0xa8, 0x66, 0xe6, 0xc5, 0x86, 0xd3, 0x96, 0x92, 0xbc, 0x03,
	0x27, 0xbf, 0x96, 0x4c, 0xa4, 0x4c, 0x0e, 0xbd, 0x73, 0x6f, 0xd4, 0x9f, 0x9c, 0xda, 0x49, 0x58,
	0x08, 0xb5, 0x6c, 0xf4, 0x87, 0x03, 0x9d, 0xaa, 0xb6, 0x57, 0xa1, 0x23, 0xd8, 0x66, 0xbe, 0xc6,
	0xba, 0x02, 0x5a, 0x05, 0xe4, 0x21, 0x9c, 0xe6, 0xc9, 0x6f, 0x7a, 0xa5, 0x1b, 0x9e, 0x16, 0x4a,
	0x62, 0x0d, 0x1e, 0x3d, 0x06, 0xc9, 0x1b, 0x00, 0x69, 0xa1, 0x98, 0xb8, 0x4b, 0xb2, 0x6f, 0xf5,
	0x8a, 0x5a, 0xd2, 0x42, 0xc8, 0x03, 0x08, 0x70, 0xf9, 0xc7, 0x92, 0x17, 0x43, 0x1f, 0xf3, 0x37,
	0x40, 0xf4, 0x3b, 0x04, 0xf5, 0xe6, 0xc9, 0x10, 0x4e, 0x36, 0x82, 0xe7, 0x34, 0xd9, 0x9b, 0x42,
	0x6c, 0xa8, 0x0b, 0x54, 0x5c, 0xe3, 0x6e, 0x55, 0x20, 0x06, 0xe4, 0x1c, 0xfa, 0x5a, 0x30, 0xdb,
	0xf1, 0xd5, 0xcf, 0xf5, 0xda, 0x6d, 0x48, 0x2f, 0xae, 0xb8, 0xe5, 0x7d, 0xe4, 0x1b, 0x20, 0xfa,
	0x0c, 0x7a, 0x94, 0xc9, 0x1d, 0x2f, 0x24, 0x23, 0x1f, 0xc0, 0x89, 0x60, 0xb2, 0xcc, 0x94, 0x1c,
	0x3a, 0xd8, 0xb5, 0x57, 0x8e, 0xbb, 0x86, 0x1c, 0xb5, 0x9a, 0xe8, 0x2f, 0x07, 0xfa, 0x2d, 0x42,
	0x17, 0xc8, 0x84, 0xe0, 0xc2, 0x76, 0x10, 0x83, 0xa6, 0xaf, 0x6e, 0xbb, 0xaf, 0x67, 0xd0, 0xcb,
	0x99, 0x4a, 0xb0, 0x21, 0x1e, 0x12, 0x75, 0x4c, 0xde, 0x83, 0xae, 0xac, 0xce, 0xce, 0xc7, 0x2a,
	0x48, 0xdb, 0x22, 0xb7, 0xc8, 0x50, 0xa3, 0x20, 0x6f, 0x41, 0x57, 0x25, 0xcb, 0x8c, 0xc9, 0x61,
	0xe7, 0xf8, 0x9c, 0x63, 0x8d, 0x52, 0x43, 0x46, 0x3f, 0x42, 0x07, 0x01, 0xbd, 0xc5, 0x15, 0xcf,
	0xca, 0xbc, 0x78, 0x6e, 0x8b, 0xc8, 0x7f, 0x85, 0x1c, 0xb5, 0x1a, 0xf2, 0x10, 0x7c, 0xc1, 0xf7,
	0xfa, 0xd4, 0xb5, 0x36, 0x3c, 0x4e, 0xce, 0xf7, 0x14, 0xd9, 0xe8, 0x4d, 0xe8, 0xb7, 0x66, 0x13,
	0x02, 0x7e, 0x91, 0xe4, 0xcc, 0xb4, 0x01, 0xc7, 0xd1, 0x05, 0xf4, 0xec, 0x24, 0x32, 0x82, 0xee,
	0x5d, 0x92, 0x95, 0xcc, 0x96, 0x50, 0xa7, 0xa5, 0x7c, 0xff, 0xbd, 0x26, 0xa8, 0xe1, 0xa3, 0x7f,
	0x5d, 0xe8, 0x59, 0x90, 0xbc, 0x0b, 0xfe, 0xb3, 0xb4, 0xa8, 0xfc, 0x39, 0x98, 0xbc, 0x76, 0x7f,
	0xd2, 0xf8, 0x9b, 0xb4, 0x58, 0x53, 0x94, 0x68, 0x53, 0xac, 0x79, 0xb9, 0xcc, 0x18, 0x32, 0xd8,
	0x79, 0x87, 0xb6, 0x21, 0xe3, 0xd8, 0xcb, 0x8b, 0x4a, 0xd0, 0x38, 0xd6, 0x20, 0xda, 0x34, 0x4b,
	0xce, 0xb3, 0x8a, 0xd6, 0xa6, 0xe9, 0xd1, 0x06, 0xd0, 0xf9, 0xa5, 0x12, 0x69, 0xb1, 0xad, 0xf8,
	0x0e, 0x6e, 0xb4, 0x0d, 0xe9, 0xfc, 0xcb, 0x83, 0x62, 0xb2, 0x12, 0x74, 0xcf, 0x9d, 0xd1, 0x8b,
	0xb4, 0x85, 0x44, 0x1b, 0xf0, 0x75, 0xbd, 0xe4, 0x14, 0x82, 0xf8, 0xe9, 0xcd, 0xec, 0xa7, 0xab,
	0x27, 0x8b, 0x45, 0xf8, 0x02, 0x79, 0x09, 0xfa, 0x18, 0x3e, 0xba, 0x7e, 0x32, 0x5d, 0xcc, 0x42,
	0x87, 0x0c, 0x00, 0x10, 0x98, 0x5f, 0xc5, 0x97, 0x17, 0xa1, 0x5b, 0xeb, 0xa7, 0xd7, 0xd7, 0x8b,
	0xd0, 0xab, 0xf5, 0xb7, 0x31, 0x9d, 0x5f, 0x7d, 0x1d, 0xfa, 0xb5, 0x7e, 0xfa, 0x34, 0x9e, 0xdd,
	0x86, 0x9d, 0xe8, 0x1f, 0x07, 0x06, 0xc7, 0xef, 0x04, 0x19, 0x80, 0x9b, 0x56, 0x5d, 0xf4, 0xa8,
	0x9b, 0xae, 0xb5, 0x41, 0xb9, 0xd8, 0x1a, 0x83, 0x7a, 0xb4, 0x0a, 0xea, 0x43, 0xf4, 0x9a, 0x43,
	0xd4, 0x98, 0x3a, 0xec, 0x98, 0xb9, 0xc1, 0x38, 0x26, 0x21, 0x78, 0xa5, 0xc8, 0x4c, 0x0b, 0xf4,
	0x50, 0x5b, 0xfb, 0x17, 0xc9, 0x0b, 0xbd, 0x2a, 0x6e, 0x3c, 0xa0, 0x75, 0x4c, 0xde, 0x86, 0x81,
	0x64, 0xab, 0x52, 0xb0, 0xc7, 0x56, 0x71, 0x82, 0x8a, 0x7b, 0x68, 0xf4, 0xb7, 0x03, 0xd0, 0xb8,
	0xfd, 0xff, 0x1c, 0x45, 0x3e, 0x02, 0x5f, 0x25, 0x5b, 0x6b, 0xcd, 0x07, 0xcf, 0xdf, 0x91, 0x71,
	0x9c, 0x6c, 0xe5, 0xac, 0x50, 0xe2, 0x40, 0x51, 0xa9, 0xef, 0xca, 0xae, 0x7a, 0xc4, 0xee, 0xbd,
	0x89, 0xf8, 0x8a, 0x51, 0x43, 0x9e, 0x7d, 0x02, 0x41, 0x3d, 0x53, 0x6f, 0xef, 0x19, 0x3b, 0x98,
	0x85, 0xf5, 0x50, 0xb7, 0xeb, 0xae, 0x76, 0x55, 0x40, 0xab, 0xe0, 0x73, 0xf7, 0x53, 0x27, 0xfa,
	0x02, 0x3a, 0x98, 0x09, 0x5f, 0x9c, 0x34, 0x67, 0x52, 0x25, 0xf9, 0xce, 0x34, 0xba, 0x01, 0x8e,
	0x13, 0x38, 0x26, 0xc1, 0xe4, 0x4b, 0x08, 0x9b, 0x73, 0xba, 0xc9, 0xca, 0x6d, 0x5a, 0x90, 0xf7,
	0xed, 0xdb, 0xdc, 0x7c, 0x12, 0xf6, 0x2b, 0x39, 0x6b, 0x2e, 0x8d, 0x79, 0xbd, 0xa6, 0xbd, 0x1f,
	0xcc, 0xa7, 0xb3, 0xec, 0xe2, 0x1f, 0xf4, 0xf1, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xe9,
	0xcb, 0xff, 0x97, 0x06, 0x00, 0x00,
}
